version: "3"

services:
  stats_events:
    image: yandex/clickhouse-server:21.3.2.5
    restart: always
    networks:
      - stats_internal
    volumes:
      - ./data:/var/lib/clickhouse
      - ./clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse-user.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  stats:
    image: plausible/analytics:latest
    container_name: stats
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - stats_internal
      - traefik-proxy
    labels:
      traefik.enable: true
      traefik.http.routers.stats.entrypoints: https
      traefik.http.services.stats.loadbalancer.server.port: 8000
    environment:
      BASE_URL: ${BASE_URL:?error}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:?error}
      DATABASE_URL: ${DATABASE_URL:?error}
      CLICKHOUSE_DATABASE_URL: http://stats_events:8123/plausible_events_db
      DISABLE_AUTH: "true"
      DISABLE_REGISTRATION: "true"
      ADMIN_USER_EMAIL: luca@castelnuovo.xyz
      ADMIN_USER_NAME: Luca Castelnuovo
      ADMIN_USER_PWD: ${ADMIN_USER_PWD:?error}
    command: sh -c "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"

networks:
  traefik-proxy:
    driver: bridge
    external: true
  stats_internal:
    external: false
