http:
  routers:
    proxmox:
      entryPoints:
        - https
      rule: "Host(`proxmox.castelnuovo.xyz`)"
      service: proxmox

  services:
    proxmox:
      loadBalancer:
        servers:
          - url: https://teresa.ltc:8006

  middlewares:
    # Authelia guard
    auth:
      forwardauth:
        address: http://authelia:9091/api/verify?rd=https://authelia.castelnuovo.xyz/
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email

    # Authelia basic auth guard
    auth-basic:
      forwardauth:
        address: http://authelia:9091/api/verify?auth=basic
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email

    securityHeaders:
      headers:
        customResponseHeaders:
          server: ""
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
        sslProxyHeaders:
          X-Forwarded-Proto: https
        hostsProxyHeaders:
          - X-Forwarded-Host
        customRequestHeaders:
          X-Forwarded-Proto: https
        customResponseHeaders:
          X-Forwarded-Proto: https
        referrerPolicy: same-origin
        contentTypeNosniff: true
        browserXssFilter: true
        frameDeny: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true
        # permissionsPolicy: ""

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
