version: "3"

services:
  fusionauth:
    image: fusionauth/fusionauth-app:latest
    container_name: fusionauth
     restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-proxy
    labels:
      traefik.enable: true
      traefik.http.routers.email.entryPoints: https
      traefik.http.services.email.loadbalancer.server.port: 9011
    volumes:
      - ./config:/usr/local/fusionauth/config
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/fusionauth
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_ROOT_USERNAME: ${DATABASE_USERNAME_ROOT}
      DATABASE_ROOT_PASSWORD: ${DATABASE_PASSWORD_ROOT}
      FUSIONAUTH_APP_MEMORY: 512M
      FUSIONAUTH_APP_RUNTIME_MODE: production
      FUSIONAUTH_APP_URL: https://fusionauth.castelnuovo.xyz
      SEARCH_TYPE: database
    ports:
      - 9011:9011
