version: "3"

services:
  teleport:
    image: quay.io/gravitational/teleport:10.0.2
    container_name: teleport
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-proxy
    labels:
      traefik.enable: true
      traefik.http.routers.teleport.entryPoints: https
      traefik.http.services.teleport.loadbalancer.server.port: 443
      traefik.http.services.teleport.loadbalancer.server.scheme: https
    volumes:
      - ./config:/etc/teleport
      - ./data:/var/lib/teleport
    ports:
      - 3022:3022
      - 3023:3023
      - 3025:3025
    # hostname: luna.teleport

networks:
  traefik-proxy:
    driver: bridge
    external: true
